@startuml
skin rose
skinparam style strictuml

participant TextBasedGame
participant Highscore
participant FileSystem
participant HighscoreFile

create Highscore
TextBasedGame -> Highscore: init(path_to_file)
Highscore -> FileSystem: open(path_to_file)
alt file exists
    create HighscoreFile
    FileSystem -> HighscoreFile: read file
    activate HighscoreFile
    HighscoreFile --> FileSystem: return content
    deactivate HighscoreFile
    FileSystem --> Highscore: set highscore_data to file content
else file not found
    FileSystem --> Highscore: set highscore_data empty
end
TextBasedGame -> Highscore: update(score)
alt highscore_data empty
    Highscore -> FileSystem: create HighscoreFile
    create HighscoreFile
    FileSystem -> HighscoreFile: create HighscoreFile
    activate HighscoreFile
    HighscoreFile --> FileSystem: created
    FileSystem --> Highscore: created
end
Highscore -> FileSystem: write new highscore_date into file
FileSystem -> HighscoreFile: write new highscore_date into file
HighscoreFile --> FileSystem: success
deactivate HighscoreFile
TextBasedGame -> Highscore: print()
activate Highscore
loop iterate over highscore_data
    Highscore -> Highscore: print score
end
Highscore --> TextBasedGame: print highscore
deactivate Highscore
@enduml