@startuml
skin rose
skinparam style strictuml

participant GraphicsBasedGame
participant Highscore
participant FileSystem
participant HighscoreFile

create Highscore
GraphicsBasedGame -> Highscore: init(path_to_file)
Highscore -> FileSystem: open(path_to_file)
alt file exists
    create HighscoreFile
    FileSystem -> HighscoreFile: read file
    activate HighscoreFile
    HighscoreFile --> FileSystem: return content
    deactivate HighscoreFile
    FileSystem --> Highscore: set highscore_data to file content
else file not found
    FileSystem --> Highscore: set highscore_data empty
end
GraphicsBasedGame -> Highscore: update(score)
alt highscore_data empty
    Highscore -> FileSystem: create HighscoreFile
    create HighscoreFile
    FileSystem -> HighscoreFile: create HighscoreFile
    activate HighscoreFile
    HighscoreFile --> FileSystem: created
    FileSystem --> Highscore: created
end
Highscore -> FileSystem: write new highscore_date into file
FileSystem -> HighscoreFile: write new highscore_date into file
HighscoreFile --> FileSystem: success
FileSystem --> Highscore: success
deactivate HighscoreFile
GraphicsBasedGame -> Highscore: draw highscore
activate Highscore
loop iterate over sorted highscore keys
    Highscore -> Highscore: print name and score
end
Highscore --> GraphicsBasedGame: highscore drawn
deactivate Highscore
@enduml