```plantuml
@startuml

start

:Create Menu;
:Run Menu;
repeat :Game Loop;
  :Print menu;
  repeat :Ask player for input;
  repeat while (wrong input) is (True)
  switch (input)
    case (a)
        :Run TextBasedGame;
    case (b)
        :Display Highscore;
    case (c)
        :quit;
        end
    endswitch
repeat while
@enduml
```