@startuml
skin rose
skinparam style strictuml

participant TextBasedGame
participant Question
participant Answers

TextBasedGame -> Question: current_question.get_options():
loop iterate over amount of answers
  Question -> Answers: get current answer index
  Answers --> Question: index
  Question -> Question: get letter of index
  Question -> Question: add letter to options
end
Question --> TextBasedGame: return options
@enduml